### ISSUE TITLE
How can I change the node priority color?

### ISSUE THREAD

**Issue by wujlin** [PavlopoulosLab/Arena3Dweb#13]

**Comment by vagkaratzas** [comment]
Two options for this, from which you can select one through the UI, in the Node Actions tab:
Color Priority:
1. Default / Imported, or 2. Clustering

To hand pick node colors there are two ways to go about it; either use the API to send your json file with "nodes" "color" attribute given, or upload your node attributes file from the File tab. Check out the Help tab for more info (API, Input & Output Files)!
