### ISSUE TITLE
API availability in local install

### ISSUE THREAD

**Issue by molcentrics** [PavlopoulosLab/Arena3Dweb#16]
Hello, 

Is the API available in the local install? The help suggests https://bib.fleming.gr/bib/api/arena3dweb however I'm not sure how to do it with the local version at http://localhost:3838.

Thanks,
Doug

**Comment by vagkaratzas** [comment]
Hey,

I am afraid that the API functionality is only usable for the online version of the tool, as the API handler is a separate resource developed in our lab, outside the Arena3Dweb repo.
